name: "CMake - Linux-GCC"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release
  CC: gcc-8
  CXX: g++-8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Update compilers
      shell: bash
      run: |
        sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -yq install g++-8 gcc-8

    - name: Configure CMake
      shell: bash
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX

    - name: Build
      shell: bash
      run: |
        cmake --build build --config $BUILD_TYPE

    - name: Tests
      shell: bash
      run: |
        chmod u+x .github/launch-tests
        bash .github/launch-tests

    - name: Organize files for upload
      shell: bash
      run: |
        mkdir artifact
        cp build/@ProjectName@ artifact

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-gcc-version
        path: artifact