name: "CMake - MSVC"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release
  CC: cl
  CXX: cl

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        config:
        - {
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      shell: bash
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX

    - name: Build
      shell: bash
      run: |
        cmake --build build --config $BUILD_TYPE

    - name: Tests
      shell: bash
      run: |
        chmod u+x .github/launch-tests
        bash .github/launch-tests

    - name: Organize files for upload
      shell: bash
      run: |
        mkdir artifact
        cp build/$BUILD_TYPE/@ProjectName@.exe artifact

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-msvc-version
        path: artifact
